"use client";

import { useState } from "react";
import { Stethoscope, Printer, CheckSquare, ArrowRight, FileText, Shield } from "lucide-react";
import { concerns, questionsToAsk, parentRights } from "@/data/doctor-prep";
import { useChildProfile } from "@/lib/stores/child-profile";
import { PrintControls } from "@/components/ui/print-controls";
import { FadeIn, StaggerChildren, StaggerItem } from "@/components/motion";

export default function DoctorPrepPage() {
  const { childAgeMonths, childName } = useChildProfile();
  const [selectedConcerns, setSelectedConcerns] = useState<Set<string>>(new Set());
  const [showSummary, setShowSummary] = useState(false);

  const toggleConcern = (id: string) => {
    setSelectedConcerns(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  };

  const selected = concerns.filter(c => selectedConcerns.has(c.id));

  if (showSummary && selected.length > 0) {
    return (
      <div className="max-w-2xl space-y-6">
        <div className="flex items-center justify-between">
          <button onClick={() => setShowSummary(false)} className="text-sm text-muted-foreground hover:text-foreground">&larr; Back</button>
          <PrintControls targetId="doctor-prep-print" />
        </div>

        {/* Printable summary */}
        <div className="rounded-2xl border bg-card p-6 space-y-6 print:border-0 print:p-0" id="doctor-prep-print">
          <div className="text-center border-b pb-4">
            <h1 className="font-heading text-xl font-bold">Pediatrician Visit Prep Sheet</h1>
            <p className="text-sm text-muted-foreground">
              {childName ? `For: ${childName}` : "For my child"}{childAgeMonths ? ` (${childAgeMonths} months old)` : ""} — {new Date().toLocaleDateString()}
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="font-heading font-semibold text-sm">My Concerns</h2>
            {selected.map(c => (
              <div key={c.id} className="rounded-lg bg-muted/50 p-3 space-y-1.5 text-sm">
                <p className="font-medium">{c.label}</p>
                <p className="text-muted-foreground"><strong>What to say:</strong> {c.whatToTellDoctor}</p>
                <p className="text-muted-foreground"><strong>What to ask:</strong> {c.whatToAsk}</p>
              </div>
            ))}
          </div>

          <div className="space-y-2">
            <h2 className="font-heading font-semibold text-sm">Questions to Ask</h2>
            <ul className="space-y-1.5 text-sm">
              {questionsToAsk.map((q, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="w-5 h-5 rounded border shrink-0 mt-0.5" />
                  <span>{q}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="space-y-2 rounded-lg bg-sage-50 border border-sage-200 p-4">
            <h2 className="font-heading font-semibold text-sm flex items-center gap-2 text-sage-800">
              <Shield className="w-4 h-4" /> Your Rights as a Parent
            </h2>
            <ul className="space-y-2 text-sm text-sage-800">
              {parentRights.map((r, i) => (
                <li key={i}>
                  <p className="font-medium">{r.title}</p>
                  <p className="text-xs text-sage-700">{r.description}</p>
                </li>
              ))}
            </ul>
          </div>

          <p className="text-xs text-muted-foreground italic text-center">
            This prep sheet was generated by HomeSLP, an educational platform. It is not a clinical document. The suggestions below are conversation starters, not medical recommendations.
          </p>
        </div>
      </div>
    );
  }

  // Step 1: Select concerns
  return (
    <div className="max-w-2xl space-y-6">
      <FadeIn>
        <div className="flex items-center gap-3">
          <Stethoscope className="w-7 h-7 text-primary" />
          <h1 className="font-heading text-2xl font-bold sm:text-3xl">Talk to Your Doctor</h1>
        </div>
        <p className="mt-1.5 text-muted-foreground">Select your concerns and we&apos;ll create a prep sheet you can print and bring to your appointment.</p>
      </FadeIn>

      <FadeIn delay={0.1}>
        <p className="text-sm font-medium">What concerns do you have? (Select all that apply)</p>
      </FadeIn>

      <StaggerChildren className="space-y-2">
        {concerns.map(c => (
          <StaggerItem key={c.id}>
            <button
              onClick={() => toggleConcern(c.id)}
              className={`w-full rounded-xl border p-4 text-left text-sm transition-all ${
                selectedConcerns.has(c.id)
                  ? "border-primary bg-primary/5 shadow-warm-sm"
                  : "border-border bg-card hover:border-primary/30"
              }`}
            >
              <div className="flex items-center gap-3">
                <div className={`w-5 h-5 rounded border-2 flex items-center justify-center shrink-0 ${
                  selectedConcerns.has(c.id) ? "border-primary bg-primary" : "border-muted-foreground/30"
                }`}>
                  {selectedConcerns.has(c.id) && <CheckSquare className="w-3.5 h-3.5 text-primary-foreground" />}
                </div>
                <div>
                  <span className="font-medium">{c.label}</span>
                  <span className="text-xs text-muted-foreground capitalize ml-2 rounded-full bg-muted px-2 py-0.5">{c.category}</span>
                </div>
              </div>
            </button>
          </StaggerItem>
        ))}
      </StaggerChildren>

      {selectedConcerns.size > 0 && (
        <FadeIn>
          <button
            onClick={() => setShowSummary(true)}
            className="w-full inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-6 py-3 text-sm font-medium text-primary-foreground shadow-warm-sm hover:bg-primary/90"
          >
            <FileText className="w-4 h-4" /> Generate My Prep Sheet
            <ArrowRight className="w-4 h-4" />
          </button>
        </FadeIn>
      )}
    </div>
  );
}
